repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: name-tests-test
    -   id: debug-statements
    -   id: requirements-txt-fixer
# Run linter and formatter.
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.5.5'
    hooks:
    -   id: ruff
        args: ['--fix']
    -   id: ruff-format
# Run the type checker.
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
    -   id: mypy