{% set project = load_file_data('../pyproject.toml', from_recipe_dir=True).get('project') %}

package:
    name: {{ project.get('name') }}
    version: "{{ environ['PACKAGE_VERSION'] }}"

build:
    number: 0
    script: "{{ PYTHON }} -m pip install . -vv"
    entry_points:
        {% for name, script in project.get('scripts').items() %}
        - {{ name }} = {{ script }}
        {% endfor %}

source:
    path: ../

requirements:
    host:
        - python
        - pip
        - setuptools >=80
        - setuptools-scm >=8
    run:
        {% for dep in project.get('dependencies') %}
        - {{ dep }}
        {% endfor %}

test:
    imports:
        - um2nc
    commands:
    {% for name, script in project.get('scripts').items() %}
        - {{ name }} --help
    {% endfor %}

about:
    home: {{ project.get('urls').get('Repository') }}
    license: Apache Software
    license_file: LICENSE
    summary: {{ project.get('description') }}
    license_family: Apache

