name: CD

on:
  push:
    tags:
      - '*'

jobs:
  check-version:
    name: Check version
    runs-on: ubuntu-latest
    steps:
      - name: Check version
        uses: access-nri/actions/.github/actions/version-check@main
        with: 
          versioning-scheme: semver

  get-package-name:
    name: Get package name
    runs-on: ubuntu-latest
    outputs:
        package-name: ${{ steps.get-package-name.outputs.package-name }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v6
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Get name
        id: get-package-name
        run: |
          echo "package-name=$(yq '.project.name' pyproject.toml)" >> $GITHUB_OUTPUT

  ci:
    name: Run CI tests
    uses: ./.github/workflows/CI.yml
    
  release-conda-package:
    name: Build with conda and upload
    runs-on: ubuntu-latest
    needs: [check-version, get-package-name, ci]
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v6
        with:
            fetch-tags: true
            fetch-depth: 0 

      - name: Setup conda build environment
        uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v3.0.0
        with:
          environment-file: .conda/env_build.yml
          create-args: >-
            python=${{vars.PY_VERSION}}
      
      # conda build cannot get the version from setuptools_scm so we have 
      # to set it in an env var (PACKAGE_VERSION) prior to building 
      # and use it in the meta.yaml
      - name: Get package version
        id: get-version
        shell: micromamba-shell {0}
        run: |
          version=$(python3 -m setuptools_scm) 
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Build and upload conda package
        id: build-and-upload
        env:
          PACKAGE_VERSION: ${{ steps.get-version.outputs.version }}
        uses: ACCESS-NRI/action-build-and-upload-conda-packages@v3.1.0
        with:
          meta_yaml_dir: .conda
          user: ${{ secrets.ANACONDA_USER_NAME }}
          token: ${{ secrets.ANACONDA_TOKEN }}
          label: main
          conda_build_args: -c accessnri -c conda-forge -c nodefaults
      
      - name: Re-format output paths
        id: reformat-paths
        run: |
            paths=$(tr ' ' '\n' <<< "${{steps.build-and-upload.outputs.paths}}")
            echo "newline-separated-paths=$paths" >> $GITHUB_OUTPUT
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: conda-packages
          path: ${{steps.reformat-paths.outputs.newline-separated-paths}}

  create-binary-executable:
    name: Create binary executable
    needs: release-conda-package
    uses: ./.github/workflows/create_binary.yml
    secrets: inherit
    
  create-github-release:
    runs-on: ubuntu-latest
    name: Create GitHub release with conda packages and binary executable
    needs: [get-package-name, create-binary-executable]
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        id: download-artifacts
        with:
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda #v3.0.0
        with:
          tag_name: test
          name: ${{needs.get-package-name.outputs.package-name}} test
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: ${{steps.download-artifacts.outputs.download-path}}/*