on:
  workflow_call:
    inputs:
      version:
        type: string
        description: |
          Version of um2nc to be used in the binary executable.
          If not provided, the development version from the `github.sha` commit will be used.
        required: false
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: |
          Version of um2nc to be used in the binary executable.
          If not provided, the development version from the `github.sha` commit will be used.
        required: false

jobs:
  create-binary-executable:
    name: Create binary executable
    runs-on: ubuntu-latest
    environment: gadi
    env:
      MICROMAMBA_DOWNLOAD_URL: https://micro.mamba.pm/api/micromamba/linux-64/latest
      UM2NC_DIST_DIR: ${{ secrets.UM2NC_DIST_DIR }}_${{ github.run_id }}
      PYINSTALLER_SPEC_PATH: binary_dist/pyinstaller.spec
      REPO_URL: ${{ github.server_url }}/${{ github.repository }}.git
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.sha }}

      - name: Set up SSH
        uses: access-nri/actions/.github/actions/setup-ssh@main
        with:
          hosts: "${{ secrets.HOST }}:gadi"
          user: ${{ secrets.USER }}
          private-key: ${{ secrets.SSH_KEY }}
        
      - name: Create executable
        id: create-executable
        run: |
          ssh gadi << 'GADI_SSH_EOF'
          set -exo pipefail
          work_dir=$(mktemp -d)
          trap "rm -rf $work_dir" EXIT
          repo_dir="$work_dir"/'${{ github.event.repository.name }}'
          # Clone the repository on Gadi
          git clone '${{ env.REPO_URL }}' "$repo_dir"
          cd "$repo_dir"
          echo "Setting up pyinstaller environment"
          export MAMBA_EXE=$work_dir/micromamba
          export MAMBA_ROOT_PREFIX=$work_dir/mamba_root
          # Download micromamba
          echo "Downloading latest micromamba version"
          curl -L ${{ env.MICROMAMBA_DOWNLOAD_URL }} | tar -xvjO bin/micromamba > "$MAMBA_EXE"
          chmod u+x "$MAMBA_EXE"
          "$MAMBA_EXE" --version
          # Create conda environment and install pyinstaller
          env_prefix="$work_dir/pyinstaller"
          git fetch origin '${{ github.sha }}'
          git checkout FETCH_HEAD
          if [[ -n "${{ inputs.version }}" ]]; then
            $MAMBA_EXE create \
              -y \
              --prefix $env_prefix \
              --no-rc \
              -c accessnri \
              -c conda-forge \
              -c nodefaults \
              pyinstaller \
              um2nc==${{ inputs.version }}
            else
              $MAMBA_EXE create \
                -y \
                --prefix $env_prefix \
                --no-rc \
                -f .conda/env_dev.yml
              # Install pyinstaller and um2nc
              "$MAMBA_EXE" run \
                --prefix $env_prefix \
                pip install . pyinstaller --no-build-isolation
          fi
          # Create binary executable with pyinstaller
          dist_dir="$work_dir/dist"
          $MAMBA_EXE run \
            --prefix $env_prefix \
            pyinstaller "${{ env.PYINSTALLER_SPEC_PATH }}" --distpath "$dist_dir"
          # Find the created executable and test it
          UM2NC_EXE=$(find "$dist_dir" -type f -name 'um2nc*' -exec realpath {} \;)
          # Test the binary executable
          echo "Testing the binary executable..."
          version=$("$UM2NC_EXE" --version)
          echo "um2nc version: $version"
          bash integration/regression_tests.sh \
            --exe "$UM2NC_EXE" \
            -q \
            -d full
          # Move the created executable to a shared location on Gadi
          mkdir -p '${{ env.UM2NC_DIST_DIR }}'
          mv "$UM2NC_EXE" '${{ env.UM2NC_DIST_DIR }}'
          GADI_SSH_EOF
          echo "um2nc-version=$version" >> $GITHUB_OUTPUT

      # Copy the executable from Gadi to the local runner
      - name: Copy executable
        id: copy-executable
        run: |
          um2nc_exe_dir='${{ github.workspace }}/um2nc_dist'
          mkdir -vp "$um2nc_exe_dir"
          rsync gadi:'${{ env.UM2NC_DIST_DIR }}'/* "$um2nc_exe_dir"
          # Delete the executable from Gadi after copying it to the GitHub runner
          ssh gadi 'rm -vrf ${{ env.UM2NC_DIST_DIR }}'
          um2nc_exe_on_github_runner=$(
            find "$um2nc_exe_dir" -type f -name 'um2nc*' -exec realpath {} \;
          )
          um2nc_exe_on_github_runner_basename=$(basename "$um2nc_exe_on_github_runner")
          echo "um2nc-exe-path=$um2nc_exe_on_github_runner" >> $GITHUB_OUTPUT
          echo "um2nc-exe-name=$um2nc_exe_on_github_runner_basename" >> $GITHUB_OUTPUT
        
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.copy-executable.outputs.um2nc-exe-name }}
          path: ${{ steps.copy-executable.outputs.um2nc-exe-path }}
