description: |
  Workflow to deploy the um2nc module on Gadi as either STABLE (release)
  or DEVELOPMENT (prerelease).

on:
  workflow_call:
    inputs:
      version:
        type: string
        description: Version of the module to deploy (e.g., 1.0.0).
        required: true
      is_stable:
        description: |
          true for STABLE environments, false for DEVELOPMENT environments.
          Default is false.
        type: boolean
        default: false
        required: false
    outputs:
      exe-artifact-id:
        description: The artifact ID of the uploaded executable artifact.
        value: ${{ jobs.deploy-module.outputs.exe-artifact-id }}

defaults:
  run:
    shell: bash --noprofile --norc -xeuo pipefail {0}

jobs:
  get-date:
    name: Get current date
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.get-date.outputs.date }}
    steps:
      - name: Get date
        id: get-date
        run: |
          date=$(TZ='Australia/Sydney' date '+%FT%T %Z')
          echo "date=$date" >> "$GITHUB_OUTPUT"

  deploy-module:
    name: Deploy module
    runs-on: ubuntu-latest
    environment: gadi
    needs: get-date
    outputs:
      exe-artifact-id: ${{ steps.upload-artifact.outputs.artifact-id }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up SSH
        uses: access-nri/actions/.github/actions/setup-ssh@main
        with:
          hosts: ${{ secrets.HOST }}:hpc
          user: ${{ secrets.USER }}
          private-key: ${{ secrets.SSH_KEY }}
  
      # We create a temporary directory on the HPC system, to exchange files between
      # the GitHub runner and the HPC system.
      # We also define the path to the correspective directory and other useful files
      # on the GitHub runner so we can use them in subsequent steps both within the HPC
      # system and the GitHub runner.
      - name: Create temporary exchange directory on HPC system
        id: create-exchange-dir
        shell: bash
        run: |
          temp_exchange_dir=$(
            ssh hpc 'mktemp -d'
          )
          echo "TEMP_EXCHANGE_DIR=$temp_exchange_dir" >> $GITHUB_ENV
          # Set the path to the temporary exchange directory on the GitHub runner
          temp_exchange_dir_on_gh_runner="${{github.workspace}}/from_hpc"
          echo "TEMP_EXCHANGE_DIR_ON_GH=$temp_exchange_dir_on_gh_runner" >> $GITHUB_ENV
          # Set the name of the deployment info JSON file
          deployment_info_json_filename=deployment_info.json
          # Set the path to the deployment_info.json file on the HPC
          echo "DEPLOYMENT_INFO_JSON_ON_HPC=$temp_exchange_dir/$deployment_info_json_filename" >> $GITHUB_ENV
          # Set the path to the deployment_info.json file on the GH runner
          echo "DEPLOYMENT_INFO_JSON_ON_GH=$temp_exchange_dir_on_gh_runner/$deployment_info_json_filename" >> $GITHUB_ENV
          # Path to the repository clone on the HPC system
          echo "REPO_PATH=$temp_exchange_dir/repository_clone" >> $GITHUB_ENV

      # We create a bash script to export variables from
      # the GitHub runner environment to the HPC system
      - name: Set GitHub runner environment export script
        shell: bash
        env:
          STABLE_PRODUCTION_BASE_DIR: ${{ vars.STABLE_PRODUCTION_BASE_DIR }}
          MODULE_NAME: um2nc
          MODULE_VERSION: ${{ inputs.version }}
          GROUP_OWNER: ${{ vars.GROUP_OWNER }}
          PBS_PROJECT: ${{ vars.PBS_PROJECT }}
          PBS_STORAGE: ${{ vars.PBS_STORAGE }}
          JQ_EXE: ${{ vars.JQ_EXE }}
          STARTED_AT: ${{ needs.get-date.outputs.date }}
          ENV_TYPE: ${{ inputs.is_stable == true && 'STABLE' || 'DEVELOPMENT' }}
          HPC_TARGET: gadi
          DEPLOYMENT_INFO_JSON_PATH: ${{ env.DEPLOYMENT_INFO_JSON_ON_HPC }}
          REPO_PATH: ${{ env.REPO_PATH }}
        run: |
          # Set GitHub runner environment export script path within the HPC system
          gh_env_export_script_on_hpc="$TEMP_EXCHANGE_DIR/gh_env_exports.sh"
          gh_env_export_script_on_gh_runner=gh_env_exports_on_gh_runner.sh
          # Generate GitHub runner environment export script
          source binary_dist/scripts/github_runner_env_export.sh > "$gh_env_export_script_on_gh_runner"
          echo "GH_ENV_EXPORT_SCRIPT=$gh_env_export_script_on_hpc" >> $GITHUB_ENV
          # Copy the GitHub runner environment export script to the HPC system
          rsync "$gh_env_export_script_on_gh_runner" hpc:"$gh_env_export_script_on_hpc"
            
      # We clone the repository to make the repository files available within the HPC system.
      # For simplicity, instead of actually cloning the whole repository, we just initialise
      # an empty git repository, add the remote, fetch the specific commit and check it out.
      # This saves time and disk space, especially for large repositories.
      - name: Clone repository on HPC system
        id: clone-repo
        shell: bash
        env:
          GITHUB_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
        run: |
          ssh hpc << 'HPC_SSH_EOF'
            set -xeuo pipefail
            repo_path='${{ env.REPO_PATH }}'
            # Initialise an empty git repository 
            git init "$repo_path"
            # Add remote with GH_TOKEN for authentication
            git -C "$repo_path" \
              remote add origin 'https://x-access-token:${{ secrets.ACTIONS_READ_TOKEN }}@github.com/${{ github.repository }}.git'
            # Fetch the specific commit and check it out
            git -C "$repo_path" \
              fetch --depth 1 origin '${{ env.GITHUB_SHA }}'
            git -C "$repo_path" \
              checkout FETCH_HEAD
          HPC_SSH_EOF

      - name: Deploy
        id: deploy
        run: |
          ssh hpc << 'HPC_SSH_EOF'
            set -xeuo pipefail
            # GitHub runner environment export
            source '${{ env.GH_ENV_EXPORT_SCRIPT }}'
            # Set job name prefix
            export JOB_NAME_PREFIX=deploy
            export DEPLOYMENT_STAGE=PRODUCTION
            source "$INFRA_SCRIPTS_DIR/submit_pbs_job.sh" "$INFRA_SCRIPTS_DIR/build_and_deploy.sh"
          HPC_SSH_EOF
    
      # Get files from TEMP_EXCHANGE_DIR
      - name: Get files from temporary exchange directory on HPC system
        id: get-files-from-HPC
        if: always() && !cancelled() && steps.create-exchange-dir.outcome == 'success'
        shell: bash -xeuo pipefail {0}
        run: |
          # Get files from TEMP_EXCHANGE_DIR on HPC system to GitHub runner
          mkdir -p "$TEMP_EXCHANGE_DIR_ON_GH"
          rsync \
            -avh \
            --no-perms \
            --no-owner \
            --no-group \
            hpc:"$TEMP_EXCHANGE_DIR/" "$TEMP_EXCHANGE_DIR_ON_GH"

      - name: Get executable
        id: get-executable
        if: >
          always() && !cancelled() &&
          steps.deploy.outcome == 'success' &&
          steps.get-files-from-HPC.outcome == 'success'
        run: |
          # Find um2nc exe inside the temp exchange directory on the GitHub runner
          exe_path=$(
            find "$TEMP_EXCHANGE_DIR_ON_GH" \
            -type f \
            -name um2nc* \
            -exec realpath {} \;
          )
          exe_name=$(basename "$exe_path")
          echo "exe-path=$exe_path" >> $GITHUB_OUTPUT
          echo "exe-name=$exe_name" >> $GITHUB_OUTPUT
            
      - name: Upload executable artifact
        id: upload-artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.get-executable.outputs.exe-name }}
          path: ${{ steps.get-executable.outputs.exe-path }}

      - name: Sanity check on hpc_target_deployment_info json file
        id: verify-deployment-info-json
        if: >
          always() && !cancelled() &&
          steps.get-files-from-HPC.outcome == 'success'
        run: |
          if [[ ! -f "$DEPLOYMENT_INFO_JSON_ON_GH" ]]; then
            echo "Error: Deployment info json file not found."
            exit 1
          fi

      - name: Set message for summary
        if: >
          always() && !cancelled() &&
          steps.get-files-from-HPC.outcome == 'success'
        id: set-message-summary
        uses: access-nri/containerised-environments-infra/.github/actions/set_message@main
        with:
          ref: main
          message-type: summary
          data-file: "${{ env.DEPLOYMENT_INFO_JSON_ON_GH }}"
        
      - name: Set message in the step summary
        if: always() && !cancelled() && steps.set-message-summary.outcome == 'success'
        run: cat "${{ steps.set-message-summary.outputs.message-file-path }}" >> $GITHUB_STEP_SUMMARY

      - name: Save hpc_target_deployment_info JSON as an artifact
        if: always() && !cancelled() && steps.verify-deployment-info-json.outcome == 'success'
        uses: actions/upload-artifact@v7
        with:
          path: "${{ env.DEPLOYMENT_INFO_JSON_ON_GH }}"
          name: deployment_info_um2nc_${{ inputs.version }}

      # Delete the temporary exchange directory that we created on the HPC system
      - name: Delete temporary exchange directory on HPC system
        id: delete-temp-dir
        if: always() && steps.create-exchange-dir.outcome == 'success'
        # $TEMP_EXCHANGE_DIR is evaluated within the GitHub runner
        run: ssh hpc "rm -rfv $TEMP_EXCHANGE_DIR"